# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5689715cbbbb01e06c15d043ffaf08a19e947c8971cf4da8bc4867b6085c19a3305f849807fe0249d6e92e6d62daa0b3aa71fa2d1844e22708ed92cb8e4e551b

test:
  secret_key_base: 4f71c73b848ada3f5267c7d53084eebcfdcebc72ffc7b9b9210b9eb58e272d2f575080b2e63e3551c6373d41a0f17453d6ea998c92d2e2b6e8624360adfeb93f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
